name: CICD

on:
  push:                                           # on what event is it triggered
     branches: [main]                             # what branche to monitor

jobs:
  build:
     runs-on: [ubuntu-latest]                     # what os is the server using to run this job
     steps:                                       # define steps for the build job
       - name: Checkout source
         uses: actions/checkout@v3
       - name: login to dockerhub
         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     # will extract value from github secrets
       - name: build docker image
         run: docker build -t decorjim/serverimage-docker .
       - name: publish image to dockerhub
         run: docker push decorjim/serverimage-docker

  deploy:
     needs: build                                  # job runs after build task finishes
     runs-on: [aws-ec2]
     steps:
       - name: pull image from docker hub
         run: docker pull decorjim/serverimage-docker
       - name: delete old container
         run: docker rm -f serverimage-docker-container
       - name: run docker container
         run: docker run -d -p 80:80 decorjim/serverimage-docker -name serverimage-docker-container decorjim/serverimage-docker



       
